### ISSUE TITLE
[Mechanics] - Intererence between components

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-bts#6]
There are components that sit inside one another. They can be seen below:
![image](https://user-images.githubusercontent.com/5435954/133931067-c4e9df82-d5a8-448c-bf83-a95f609104b1.png)

**Comment by mbz4** [comment]
not sure i understand, but perhaps the joinery was not up to the task
i can offset the joints in the assembly if thats the issue

the adapter rings are there because i noticed and measured an offset of about 2mm either side
Im not sure what else would cause the interference but this is what you can expect in rushed designs.

**Comment by Akustav** [comment]
The spacers seem to be placed wrong, they are 2 mm wide for a 1.7mm gap.

**Comment by Akustav** [comment]
Clsoing to review new iteration
